version: "3"
services:
  dittydog-backend:
    image: spotify-backend
    build:
      dockerfile: Dockerfile
      context: .
    container_name: spotify-backend
    env_file: ./.env
    environment:
      - FLASK_APP=backend.py
      - FLASK_ENV=development
      - FLASK_RUN_PORT=8080
    ports:
      - "80:8080"
    volumes:
      - .:/app
